import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "var(--bg)",
    fontFamily: "var(--font-body)",
    display: "flex",
    flexDirection: "column",
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: 24,
    padding: "14px 32px",
    borderBottom: "1px solid var(--border)",
    background: "color-mix(in srgb, var(--bg-raised) 78%, transparent)",
    WebkitBackdropFilter: "blur(18px) saturate(160%)",
    backdropFilter: "blur(18px) saturate(160%)",
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  brandIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    borderRadius: 10,
    background: "linear-gradient(135deg, var(--accent) 0%, var(--accent-dark) 100%)",
    boxShadow: "0 4px 12px color-mix(in srgb, var(--accent) 40%, transparent)",
  },
  brandText: {
    fontSize: 18,
    fontWeight: 700,
    color: "var(--text)",
    letterSpacing: "-0.02em",
    fontFamily: "var(--font-display)",
  },
  navLinks: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    flex: 1,
  },
  navLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "8px 14px",
    borderRadius: 999,
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
  },
  navLinkActive: {
    background: "color-mix(in srgb, var(--accent) 12%, transparent)",
    color: "var(--accent)",
    fontWeight: 600,
  },
  navRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  signInBtn: {
    padding: "8px 18px",
    fontSize: 13,
    fontWeight: 600,
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--bg-soft)",
    color: "var(--text)",
    cursor: "pointer",
  },
  signUpBtn: {
    padding: "8px 18px",
    fontSize: 13,
    fontWeight: 600,
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "linear-gradient(135deg, var(--accent) 0%, var(--accent-dark) 100%)",
    color: "var(--accent-ink)",
    cursor: "pointer",
    boxShadow: "0 4px 12px color-mix(in srgb, var(--accent) 30%, transparent)",
  },
  navUser: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  navAvatar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: "linear-gradient(135deg, var(--accent) 0%, var(--accent-dark) 100%)",
    color: "var(--accent-ink)",
    fontWeight: 700,
    fontSize: 13,
  },
  navName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text)",
  },
  signOutBtn: {
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
  },
main: {
    flex: 1,
    padding: "40px 48px 0",
    maxWidth: 1160,
    width: "100%",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: 40,
  },
hero: {
    position: "relative",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    gap: 72,
    padding: "72px 0 24px",
  },
  heroLeft: {
    position: "relative",
    zIndex: 1,
    flex: 1.05,
    minWidth: 0,
  },
  heroEyebrow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    fontWeight: 600,
    color: "var(--accent)",
    background: "color-mix(in srgb, var(--accent) 10%, transparent)",
    border: "1px solid color-mix(in srgb, var(--accent) 22%, transparent)",
    borderRadius: 999,
    padding: "6px 14px",
    marginBottom: 22,
  },
  heroEyebrowDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "var(--accent)",
    boxShadow: "0 0 0 3px color-mix(in srgb, var(--accent) 25%, transparent)",
  },
  heroTitle: {
    fontSize: 56,
    fontWeight: 800,
    lineHeight: 1.03,
    color: "var(--text)",
    letterSpacing: "-0.045em",
    margin: 0,
    marginBottom: 18,
    fontFamily: "var(--font-display)",
  },
  heroSubtitle: {
    fontSize: 17,
    lineHeight: 1.65,
    color: "var(--text-muted)",
    margin: 0,
    marginBottom: 28,
    maxWidth: 500,
  },
  heroPanel: {
    maxWidth: 500,
    borderRadius: "var(--radius-2xl)",
    padding: "10px",
    boxShadow: "var(--elev-raised)",
    display: "flex",
    flexDirection: "column",
  },
  heroForm: {
    display: "flex",
    gap: 10,
  },
  heroInput: {
    flex: 1,
    padding: "14px 18px",
    fontSize: 15,
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text)",
    outline: "none",
    minWidth: 0,
  },
  heroBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "14px 24px",
    fontSize: 14,
    fontWeight: 600,
    borderRadius: 999,
    border: "none",
    background: "var(--accent)",
    color: "var(--accent-ink)",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  joinRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    margin: "14px 8px",
  },
  divider: {
    flex: 1,
    height: 1,
    background: "var(--border)",
  },
  or: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-dim)",
    whiteSpace: "nowrap",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  joinBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "14px 22px",
    fontSize: 14,
    fontWeight: 600,
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "color-mix(in srgb, var(--bg-soft) 60%, transparent)",
    color: "var(--text)",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  codeInput: {
    fontFamily: "var(--font-mono)",
    letterSpacing: "0.16em",
    fontWeight: 700,
    textTransform: "uppercase",
    textAlign: "center",
    fontSize: 16,
  },
  heroHint: {
    margin: "10px 6px 0",
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-dim)",
    textAlign: "center",
    lineHeight: 1.5,
  },
  error: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "9px 14px",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--danger)",
    background: "color-mix(in srgb, var(--danger) 8%, transparent)",
    borderRadius: 999,
    margin: "6px 6px 0",
  },
  heroRight: {
    position: "relative",
    zIndex: 1,
    flex: 1,
    minWidth: 0,
  },
  mockFrame: {
    borderRadius: "var(--radius-2xl)",
    overflow: "hidden",
    background: "linear-gradient(160deg, #131722 0%, #0b0e16 100%)",
    border: "1px solid rgba(255,255,255,0.08)",
    boxShadow: "var(--elev-floating)",
  },
  mockTopbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 18px",
    borderBottom: "1px solid rgba(255,255,255,0.07)",
  },
  mockRec: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    fontFamily: "var(--font-mono)",
    fontSize: 11,
    letterSpacing: "0.14em",
    fontWeight: 700,
    color: "#ff5f66",
  },
  mockRecDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#ff5f66",
    boxShadow: "0 0 0 3px rgba(255,95,102,0.25)",
    animation: "pulse 1.6s ease-in-out infinite",
  },
  mockTime: {
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    letterSpacing: "0.06em",
  },
  mockIcons: {
    fontSize: 12,
    color: "rgba(255,255,255,0.4)",
    letterSpacing: "0.2em",
  },
  mockGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    padding: 14,
  },
  mockTile: {
    position: "relative",
    aspectRatio: "16/10",
    borderRadius: "var(--radius-lg)",
    background: "linear-gradient(135deg, #1b2233 0%, #121826 100%)",
    border: "1px solid rgba(255,255,255,0.06)",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  mockAvatar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 54,
    height: 54,
    borderRadius: "50%",
    color: "#fff",
    fontSize: 22,
    fontWeight: 700,
    boxShadow: "0 8px 24px rgba(0,0,0,0.45)",
  },
  mockName: {
    position: "absolute",
    bottom: 8,
    left: 8,
    fontSize: 11,
    fontWeight: 600,
    color: "rgba(255,255,255,0.92)",
    background: "rgba(10,12,18,0.55)",
    WebkitBackdropFilter: "blur(6px)",
    backdropFilter: "blur(6px)",
    padding: "3px 9px",
    borderRadius: 999,
    letterSpacing: "0.02em",
  },
  featureBand: {
    background: "var(--bg-soft)",
    borderRadius: "var(--radius-2xl)",
    padding: "56px 40px 48px",
    border: "1px solid var(--border-soft)",
  },
  featureHeader: {
    textAlign: "center",
    marginBottom: 36,
  },
  featureEyebrow: {
    display: "inline-block",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    fontWeight: 700,
    color: "var(--accent)",
    marginBottom: 12,
  },
  featureHeading: {
    fontSize: 32,
    fontWeight: 800,
    color: "var(--text)",
    letterSpacing: "-0.03em",
    margin: 0,
    fontFamily: "var(--font-display)",
  },
  featureIntro: {
    fontSize: 15,
    color: "var(--text-muted)",
    margin: "10px auto 0",
    maxWidth: 460,
  },
  features: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 18,
  },
  featureCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-xl)",
    padding: 26,
    boxShadow: "var(--elev-ring)",
    display: "flex",
    flexDirection: "column",
    textAlign: "left",
  },
  featureIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 44,
    height: 44,
    borderRadius: 14,
    background: "color-mix(in srgb, var(--accent) 12%, transparent)",
    color: "var(--accent)",
    marginBottom: 16,
  },
  featureTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text)",
    marginBottom: 6,
    fontFamily: "var(--font-display)",
    letterSpacing: "-0.01em",
  },
  featureDesc: {
    margin: 0,
    fontSize: 13.5,
    color: "var(--text-muted)",
    lineHeight: 1.6,
  },
  howSection: {
    marginTop: 24,
    padding: "44px 40px",
    borderRadius: "var(--radius-2xl)",
  },
  howHeader: {
    textAlign: "center",
    marginBottom: 32,
  },
  howTitle: {
    fontSize: 28,
    fontWeight: 800,
    color: "var(--text)",
    letterSpacing: "-0.03em",
    margin: 0,
    fontFamily: "var(--font-display)",
  },
  howSteps: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 18,
  },
  howStep: {
    textAlign: "center",
    padding: "8px 12px",
  },
  howStepNum: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "var(--accent)",
    color: "var(--accent-ink)",
    fontSize: 15,
    fontWeight: 800,
    marginBottom: 12,
    fontFamily: "var(--font-display)",
  },
  howStepTitle: {
    margin: 0,
    fontSize: 16,
    fontWeight: 700,
    color: "var(--text)",
    marginBottom: 6,
  },
  howStepDesc: {
    margin: 0,
    fontSize: 13.5,
    lineHeight: 1.55,
    color: "var(--text-muted)",
    maxWidth: 260,
    marginLeft: "auto",
    marginRight: "auto",
  },
  tableCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-xl)",
    padding: 26,
    boxShadow: "var(--elev-ring)",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: "var(--text)",
    margin: 0,
    fontFamily: "var(--font-display)",
    letterSpacing: "-0.02em",
  },
  cardMore: {
    padding: "6px 14px",
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--accent)",
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-dim)",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    padding: "10px 12px",
    borderBottom: "1px solid var(--border)",
    whiteSpace: "nowrap",
  },
  tr: {
    borderBottom: "1px solid var(--border-soft)",
  },
  td: {
    padding: "12px",
    fontSize: 14,
    color: "var(--text)",
    verticalAlign: "middle",
  },
  codePill: {
    padding: "3px 10px",
    borderRadius: 6,
    background: "color-mix(in srgb, var(--accent) 10%, transparent)",
    color: "var(--accent)",
    fontFamily: "var(--font-mono)",
    fontWeight: 700,
    fontSize: 12,
    letterSpacing: "0.06em",
  },
  tdMuted: { color: "var(--text-dim)" },
  invitedChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
    maxWidth: 220,
  },
  invitedChip: {
    padding: "2px 8px",
    borderRadius: 999,
    background: "color-mix(in srgb, var(--accent) 12%, transparent)",
    color: "var(--accent)",
    fontSize: 11,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
    padding: "44px 24px",
    borderRadius: "var(--radius-lg)",
    background: "color-mix(in srgb, var(--bg-soft) 60%, transparent)",
    border: "1px dashed var(--border)",
    textAlign: "center",
  },
  emptyIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 46,
    height: 46,
    borderRadius: "50%",
    background: "var(--bg-hover)",
    color: "var(--text-dim)",
  },
  emptyText: { fontSize: 14, color: "var(--text-dim)", margin: 0 },
  view: {
    display: "flex",
    flexDirection: "column",
    gap: 24,
  },
  viewCard: {
    background: "var(--bg-card)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-xl)",
    padding: 28,
    boxShadow: "var(--elev-ring)",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  viewTitle: { fontSize: 22, fontWeight: 800, color: "var(--text)", margin: 0, fontFamily: "var(--font-display)", letterSpacing: "-0.02em" },
  viewDesc: { fontSize: 14, color: "var(--text-muted)", margin: 0 },
  plainInput: {
    flex: 1,
    padding: "12px 16px",
    fontSize: 14,
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--bg-input)",
    color: "var(--text)",
    outline: "none",
    minWidth: 0,
  },
  schedPickRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 16,
  },
  schedPickCol: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minWidth: 0,
  },
  schedPickLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  schedSummary: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 16px",
    borderRadius: 999,
    background: "color-mix(in srgb, var(--accent) 10%, transparent)",
    border: "1px solid color-mix(in srgb, var(--accent) 26%, transparent)",
    color: "var(--accent)",
    fontSize: 13,
    fontWeight: 600,
  },
  schedSummaryIcon: { flexShrink: 0 },
  emailNote: {
    padding: "10px 16px",
    fontSize: 13,
    fontWeight: 500,
    borderRadius: 999,
    lineHeight: 1.5,
  },
  authPrompt: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    padding: "16px 0",
  },
  authPromptBtn: {
    padding: "12px 28px",
    fontSize: 14,
    fontWeight: 600,
    borderRadius: 999,
    border: "none",
    background: "var(--accent)",
    color: "var(--accent-ink)",
    cursor: "pointer",
  },
  cancelBtn: {
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 999,
    border: "1px solid color-mix(in srgb, var(--danger) 30%, transparent)",
    background: "color-mix(in srgb, var(--danger) 8%, transparent)",
    color: "var(--danger)",
    cursor: "pointer",
  },
  toast: {
    position: "fixed",
    bottom: 24,
    left: "50%",
    transform: "translateX(-50%)",
    padding: "12px 20px",
    fontSize: 14,
    fontWeight: 600,
    borderRadius: 999,
    background: "var(--text)",
    color: "var(--bg)",
    boxShadow: "var(--elev-floating)",
    zIndex: 200,
    animation: "toastIn 0.2s ease",
  },
};
