import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    background:
      "radial-gradient(ellipse 80% 60% at 50% -10%, color-mix(in srgb, var(--accent) 14%, transparent) 0%, transparent 60%), var(--bg)",
    color: "var(--text)",
  },
  body: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
    overflow: "hidden",
    position: "relative",
  },
  main: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minWidth: 0,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "12px 24px",
    borderBottom: "1px solid var(--border)",
    background: "color-mix(in srgb, var(--bg-raised) 72%, transparent)",
    WebkitBackdropFilter: "blur(18px) saturate(160%)",
    backdropFilter: "blur(18px) saturate(160%)",
    flexShrink: 0,
  },
  headerLeft: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    minWidth: 0,
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexShrink: 0,
  },
  roomCode: {
    display: "inline-flex",
    alignItems: "center",
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    letterSpacing: "0.12em",
    fontWeight: 700,
    color: "var(--accent)",
    margin: 0,
    padding: "5px 14px",
    borderRadius: 999,
    background: "color-mix(in srgb, var(--accent) 10%, transparent)",
    border: "1px solid color-mix(in srgb, var(--accent) 24%, transparent)",
  },
  participantCount: {
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 14px",
    borderRadius: 999,
    background: "color-mix(in srgb, var(--bg-soft) 80%, transparent)",
    border: "1px solid var(--border)",
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "var(--success)",
    boxShadow: "0 0 0 3px color-mix(in srgb, var(--success) 22%, transparent)",
  },
  contentArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    position: "relative",
    overflow: "hidden",
    padding: "24px 24px 16px",
  },
  mediaErrorBanner: {
    position: "absolute",
    top: 12,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 60,
    maxWidth: "min(560px, 92%)",
    padding: "10px 18px",
    fontSize: 13,
    fontWeight: 600,
    borderRadius: 999,
    color: "var(--danger)",
    background: "color-mix(in srgb, var(--danger) 10%, var(--bg-card))",
    border: "1px solid color-mix(in srgb, var(--danger) 30%, transparent)",
    boxShadow: "var(--elev-raised)",
    textAlign: "center",
  },
  sidebar: {
    flexDirection: "column",
    width: 360,
    borderLeft: "1px solid var(--border)",
    background: "color-mix(in srgb, var(--bg-raised) 92%, transparent)",
    overflow: "hidden",
    flexShrink: 0,
  },
  endedContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    background:
      "radial-gradient(ellipse 60% 50% at 50% 30%, color-mix(in srgb, var(--accent) 14%, transparent) 0%, transparent 60%), var(--bg)",
  },
  endedContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    color: "var(--text)",
    padding: "0 24px",
  },
  endedMark: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 48,
    height: 48,
    borderRadius: 16,
    background: "linear-gradient(135deg, var(--accent) 0%, var(--accent-dark) 100%)",
    boxShadow: "0 12px 32px color-mix(in srgb, var(--accent) 35%, transparent)",
    marginBottom: 18,
  },
  endedEyebrow: {
    fontFamily: "var(--font-display)",
    fontSize: 15,
    fontWeight: 800,
    letterSpacing: "-0.01em",
    color: "var(--text-muted)",
    marginBottom: 10,
  },
  endedTitle: {
    fontSize: 40,
    fontWeight: 800,
    letterSpacing: "-0.03em",
    color: "var(--text)",
    margin: 0,
    fontFamily: "var(--font-display)",
  },
  endedSub: {
    fontSize: 15,
    color: "var(--text-muted)",
    marginTop: 10,
  },
  endedButton: {
    marginTop: 28,
    padding: "13px 30px",
    fontSize: 15,
    fontWeight: 600,
    borderRadius: 999,
    border: "none",
    background: "var(--accent)",
    color: "var(--accent-ink)",
    cursor: "pointer",
  },
  endMeetingBtn: {
    position: "fixed",
    bottom: 84,
    right: 20,
    padding: "10px 24px",
    fontSize: 14,
    fontWeight: 600,
    borderRadius: 999,
    border: "none",
    background: "var(--danger)",
    color: "#fff",
    cursor: "pointer",
    zIndex: 100,
    boxShadow: "0 8px 24px color-mix(in srgb, var(--danger) 35%, transparent)",
  },
  chatToast: {
    position: "absolute",
    bottom: 16,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: 10,
    maxWidth: 420,
    padding: "10px 16px",
    borderRadius: 999,
    background: "color-mix(in srgb, var(--bg-card) 80%, transparent)",
    WebkitBackdropFilter: "blur(16px) saturate(160%)",
    backdropFilter: "blur(16px) saturate(160%)",
    border: "1px solid var(--border)",
    boxShadow: "var(--elev-raised)",
    cursor: "pointer",
    zIndex: 80,
    animation: "toastIn 0.25s ease",
  },
  chatToastSender: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--accent)",
    flexShrink: 0,
  },
  chatToastText: {
    fontSize: 13,
    color: "var(--text)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  emptyCallBanner: {
    position: "fixed",
    bottom: 100,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 18px",
    borderRadius: 12,
    background: "#202124",
    border: "1px solid rgba(255,255,255,0.12)",
    boxShadow: "0 16px 48px rgba(0,0,0,0.5)",
    zIndex: 110,
  },
  emptyCallText: {
    fontSize: 14,
    color: "#ffffff",
  },
  emptyCallStay: {
    padding: "7px 16px",
    fontSize: 13,
    fontWeight: 600,
    color: "#8ab4f8",
    background: "transparent",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
  },
  emptyCallLeave: {
    padding: "7px 18px",
    fontSize: 13,
    fontWeight: 600,
    color: "#ffffff",
    background: "#ea4335",
    border: "none",
    borderRadius: 8,
    cursor: "pointer",
  },
};
